In [ ]:
#slicing 2D elements
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [ ]:
#Slicing of 1D elements
import numpy as np
arr=np.array([2,4,6,8,10,12,14,16])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])
print(arr[:-1])

[ 8 10 12]
[ 2  4  6  8 10]
[ 6  8 10 12 14 16]
[ 8 10 12 14]
[ 2  4  6  8 10 12 14]


In [ ]:
#Python program to perform basic arithmetic operations
import numpy as np
arr=np.array([1,3,5,7,9])
sum=arr[0]+arr[2]
diff=arr[3]-arr[2]
product=arr[1]*arr[3]
div=arr[4]/arr[1]
print("sum of 2 no=",sum)
print("difference of 2 no=",diff)
print("product of 2 no=",product)
print("division of 2 no=",div)

sum of 2 no= 6
difference of 2 no= 2
product of 2 no= 21
division of 2 no= 3.0


In [ ]:
# Reshaping
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#Arrange function or Range
import numpy as np
# Fixed typo: np.arrange -> np.arange
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
import numpy as np
np.arange(1,14,4)

array([ 1,  5,  9, 13])

In [ ]:
import numpy as np
np.arange(1,3)

array([1, 2])

In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Resizing
import numpy as np
a=np.array([[1,2,3,],[4,5,6]])
print(a)
a.shape
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Copy array
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#Access the 3rd element of 2nd array of 1st array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [ ]:
#5th element of 2nd dimension
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("5th element on 2nd dim:",arr[1,4])

5th element on 2nd dim: 10


In [ ]:
#2nd element of 1st dimension
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2th element on 1st dim:",arr[0,1])


2th element on 1st dim: 2


In [ ]:
#Sum of 3rd and 4th element from the array
import numpy as np
arr=np.array([1,2,3,4,])
print(arr[2]+arr[3])

7


In [ ]:
#Elementwise arithmetic operation
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Matrics multiplication
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1@arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [ ]:
# Concatenate
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
concatenate_arr=np.concatenate((arr1,arr2),axis=0)
print(concatenate_arr)
print()
concatenate_arr=np.concatenate((arr1,arr2),axis=1)
print(concatenate_arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
concatenate_arr=np.concatenate((arr1,arr2),axis=1)
print(concatenate_arr)
print()
concatenate_arr=np.concatenate((arr1,arr2),axis=0)
print(concatenate_arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Transpose : it converts coloum into row and row into coloum (3*2--->3*2)
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print()
transpose_arr=arr.transpose()
print(transpose_arr)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Flattened : it will going to convert the multidimension into single dimension 2D to 1D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print()
flattened_arr=arr.flatten()
print(flattened_arr)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [ ]:
# To check real no and complex & scalar no
import numpy as np
a=np.array([1+1j,1+0j,4.5,3,2,2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar number:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))


Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar number:
True
False


In [ ]:
# Zeroes : gives 00
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
import numpy as np
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr=np.zeros((3,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# One : gives 1
one=np.ones(4)
one

array([1., 1., 1., 1.])

In [ ]:
one=np.ones((3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Empty : it create ramdom values and gives different values every time don't gives same
empty=np.empty(3)
empty

array([0. , 0.5, 1. ])

In [ ]:
empty=np.empty((3,2))
empty

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
import numpy as np
np.random.rand(3,2)

array([[0.14602122, 0.04173226],
       [0.13672666, 0.63867996],
       [0.57837163, 0.03782634]])

In [4]:
import numpy as np
a=np.array([1,2,3,4])
print(a.shape)

(4,)


In [6]:
import numpy as np
a=np.array([10,20,30,40])
print(a[1,0]))

SyntaxError: unmatched ')' (ipython-input-547472695.py, line 3)

In [9]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a[1,0])

3


In [10]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a.sum())

10


In [11]:
import numpy as np
a=np.array([5,10,15,20])
print(a[1:3])

[10 15]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])

In [13]:
import numpy as np
a=np.array([1,2,3,4])
print(a[-1])

4


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a.shape)

(4,)


In [14]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a[::2])

[10 30 50]


In [15]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a.T)

[[1 3]
 [2 4]]
