In [9]:
# Crop yield for 4 farmers over 5 seasons
import numpy as np
crop_yields=np.array([
    [12.5,13.2,14.1,13.8,15.2],
    [10.3,11.5,10.8,12.1,11.9],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.3,11.7,12.8]
    ])
print('crop yeild array(tons):')
print(crop_yields)
print(f'\nshape:{crop_yield.shape}')
print(f'data type:{crop_yield.dtype}')
print(f'total element:{crop_yield.size}')
print(f'dimensions:{crop_yield.ndim}')

crop yeild array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

shape:(4, 5)
data type:float64
total element:20
dimensions:2


In [6]:
# Agricultural analysis operations
import numpy as np
total_yield=np.sum(crop_yields)
avg_yeild_per_farm=np.mean(crop_yields,axis=1)
avg_yeild_per_season=np.mean(crop_yields,axis=0)
max_yeild=np.max(crop_yields)
min_yeild=np.min(crop_yields)

print(f'\ntotal production:{total_yield}tons')
print(f'average per farm:{avg_yeild_per_farm}tons')
print(f'average per season:{avg_yeild_per_season}tons')
print(f'max yeild:{max_yeild}tons')
print(f'min yeild:{min_yeild}tons')




total production:262.7tons
average per farm:[13.76 11.32 15.68 11.78]tons
average per season:[12.275 12.6   13.35  13.275 14.175]tons
max yeild:16.8tons
min yeild:10.3tons


In [13]:
# Find best performing farm
best_farm=np.argmax(avg_yeild_per_farm)
print("\nbest performing farm",best_farm+1)
print("their average yield:",round(avg_yeild_per_farm[best_farm],2),"tons")


best performing farm 3
their average yield: 15.68 tons


In [14]:
# Or
print("\nbest performing farm:farm",best_farm+1)
print("their average yield:",round(avg_yeild_per_farm[best_farm],2),"tons")


best performing farm:farm 3
their average yield: 15.68 tons


In [15]:
print(f'mean:{np.mean(crop_yields):.2f}tons/ha')
print(f'median:{np.median(crop_yields):.2f}tons/ha')
print(f'standard deviation:{np.std(crop_yields):.2f}tons/ha')

mean:13.13tons/ha
median:12.65tons/ha
standard deviation:1.89tons/ha


In [24]:
# Boolen indexing: to find exceptional yields
exceptional=crop_yield > 16
print(exceptional)

print('\nexceptional yield(>16):')
print(crop_yield[exceptional])

[[False False False False False]
 [False False False False False]
 [False False  True False  True]
 [False False False False False]]

exceptional yield(>16):
[16.2 16.8]


In [20]:
exceptional=crop_yield > 15
print(exceptional)

print('exceptional yield(>15):')
print(crop_yield[exceptional])

[[False False False False  True]
 [False False False False False]
 [ True False  True  True  True]
 [False False False False False]]
exceptional yield(>15):
[15.2 15.1 16.2 15.5 16.8]


In [22]:
# Conditional operations: classify yields
categories=np.where(crop_yield>16, 'high',
                    np.where(crop_yield>14,'medium','low'))
print('\nYield categories:')
print(categories)


Yield categories:
[['low' 'low' 'medium' 'low' 'medium']
 ['low' 'low' 'low' 'low' 'low']
 ['medium' 'medium' 'high' 'medium' 'high']
 ['low' 'low' 'low' 'low' 'low']]
